<start>::= <preprocessing> | <classification> | <ensemble>

<preprocessing> ::= <attributeSelection>
<classification> ::= <metaClassifier>
                   | <baseClassifier>
<ensemble> ::= <stackingClassifier> | <voteClassifier>

<attributeSelection> ::= <AttributeSelectedClassifier> <eval> <search>
<metaClassifier> ::= <LWL> | <AdaBoostM1> | <Bagging> | <RandomCommittee> | <RandomSubSpace>
<baseClassifier> ::= <BayesNet> | <NaiveBayes> | <NaiveBayesMultinomial> | <Logistic> | <MultiLayerPerceptron> | <SGD>
                   | <SimpleLogistic> | <SMO> | <VotedPerceptron> | <IBk> | <KStar> | <DecisionTable> | <JRip> | <OneR>
                   | <PART> | <ZeroR> | <DecisionStump> | <J48> | <LMT> | <RandomForest> | <RandomTree> | <REPTree>
<stackingClassifier> ::= <Stacking>
<voteClassifier> ::= <Vote>

<eval> ::= <CfsSubsetEval>
<search> ::= <BestFirst> | <GreedyStepwise>

<CfsSubsetEval> ::= "CfsSubsetEval"
<BestFirst> ::= "BestFirst"
<GreedyStepwise> ::= "GreedyStepwise"
<AttributeSelectedClassifier> ::= "AttributeSelectedClassifier"
<LWL> ::= "LWL"
<AdaBoostM1> ::= "AdaBoostM1"
<Bagging> ::= "Bagging"
<RandomCommittee> ::= "RandomCommittee"
<RandomSubSpace> ::= "RandomSubSpace"
<BayesNet> ::= "BayesNet"
<NaiveBayes> ::= "NaiveBayes"
<NaiveBayesMultinomial> ::= "NaiveBayesMultinomial"
<Logistic> ::= "Logistic"
<MultiLayerPerceptron> ::= "MultiLayerPerceptron"
<SGD> ::= "SGD"
<SimpleLogistic> ::= "SimpleLogistic"
<SMO> ::= "SMO"
<VotedPerceptron> ::= "VotedPerceptron"
<IBk> ::= "IBk"
<KStar> ::= "KStar"
<DecisionTable> ::= "DecisionTable"
<JRip> ::= "JRip"
<OneR> ::= "OneR"
<PART> ::= "PART"
<ZeroR> ::= "ZeroR"
<DecisionStump> ::= "DecisionStump"
<J48> ::= "J48"
<LMT> ::= "LMT"
<RandomForest> ::= "RandomForest"
<RandomTree> ::= "RandomTree"
<REPTree> ::= "REPTree"
<Stacking> ::= "Stacking"
<Vote> ::= "Vote"


