<start> ::= <preprocessing> | <classification> | <ensemble>

<preprocessing> ::= <attributeSelection> "W" <classification>
                  | <attributeSelection> "W" <ensemble>

<classification> ::= <metaClassifier> "W" <baseClassifier>
                   | <baseClassifier>

<ensemble> ::= <stackingClassifier> | <voteClassifier>

<attributeSelection> ::= <AttributeSelectedClassifier>

<metaClassifier> ::= <LWL> | <AdaBoostM1> | <Bagging> | <RandomCommittee> | <RandomSubSpace>

<baseClassifier> ::= <BayesNet> | <NaiveBayes> | <NaiveBayesMultinomial> | <Logistic> | <MultilayerPerceptron> | <SGD>
                   | <SimpleLogistic> | <SMO> | <VotedPerceptron> | <IBk> | <KStar> | <DecisionTable> | <JRip> | <OneR>
                   | <PART> | <ZeroR> | <DecisionStump> | <J48> | <LMT> | <RandomForest> | <RandomTree> | <REPTree>

<stackingClassifier> ::= <Stacking> "B" <baseClassifier>

<voteClassifier> ::= <Vote> "B" <baseClassifier>

<AttributeSelectedClassifier> ::= "AttributeSelectedClassifier"

<LWL> ::= "LWL"

<AdaBoostM1> ::= "AdaBoostM1"

<Bagging> ::= "Bagging"

<RandomCommittee> ::= "RandomCommittee"

<RandomSubSpace> ::= "RandomSubSpace"

<BayesNet> ::= "BayesNet" "D" <BayesNet-useADTree> "Q" <BayesNet-searchAlgorithm>
<BayesNet-useADTree> ::= "TRUE" | "FALSE"
<BayesNet-searchAlgorithm> ::= "K2" | "HillClimber" | "LAGDHillClimber" | "SimulatedAnnealing" | "TabuSearch" | "TAN"

<NaiveBayes> ::= "NaiveBayes" "K" <NaiveBayes-useKernelEstimator>
"K" <NaiveBayes-useKernelEstimator>::= "TRUE" | "FALSE" "D" <NaiveBayes-useSupervisedDiscretization>
<NaiveBayes-useSupervisedDiscretization> ::= "TRUE" | "FALSE"

<NaiveBayesMultinomial> ::= "NaiveBayesMultinomial"

<Logistic> ::= "Logistic" "R" <Logistic-ridge>
<Logistic-ridge> ::= "RANDOM_FLOAT [1E-12, 10]"

<MultilayerPerceptron> ::= "MultilayerPerceptron" "B" <MultilayerPerceptron-nominalToBinaryFilter>
                           "C" <MultilayerPerceptron-normalizeNumeriClass> "D" <MultilayerPerceptron-decay>
                           "H" <MultilayerPerceptron-hiddenLayers> "L" <MultilayerPerceptron-learningRate>
                           "M" <MultilayerPerceptron-momentum> "R" <MultilayerPerceptron-reset>
<MultilayerPerceptron-nominalToBinaryFilter> ::= "TRUE" | "FALSE"
<MultilayerPerceptron-normalizeNumeriClass> ::= "TRUE" | "FALSE"
<MultilayerPerceptron-decay> ::= "TRUE" | "FALSE"
<MultilayerPerceptron-hiddenLayers> ::= "a" | "i" | "o" | "t"
<MultilayerPerceptron-learningRate> ::= "RANDOM_FLOAT [0.1, 1]"
<MultilayerPerceptron-momentum> ::= "RANDOM_FLOAT [0.1, 1]"
<MultilayerPerceptron-reset> ::= "TRUE" | "FALSE"

<SGD> ::= "SGD" "F" <SGD-lossFunction> "L" <SGD-learningRate> "M" <SGD-dontReplaceMissing> "N" <SGD-dontNormalize>
                "R" <SGD-lambda>
<SGD-lossFunction> ::= "0" | "1" | "2"
<SGD-learningRate> ::= "RANDOM_FLOAT [1E-5, 0.1]"
<SGD-dontReplaceMissing> ::= "TRUE" | "FALSE"
<SGD-dontNormalize> ::= "TRUE" | "FALSE"
<SGD-lambda> ::= "RANDOM_FLOAT [1E-12, 10]"

<SimpleLogistic> ::= "SimpleLogistic" "A" <SimpleLogistic-useAIC> "S" <SimpleLogistic-useCrossValidation>
                     "W" <SimpleLogistic-weightTrimBeta>
<SimpleLogistic-useAIC> ::= "TRUE" | "FALSE"
<SimpleLogistic-useCrossValidation> ::= "TRUE" | "FALSE"
<SimpleLogistic-weightTrimBeta> ::= "0" | "RANDOM_FLOAT [0, 1]"

<SMO> ::= "SMO" "C" <SMO-cost> "K" <SMO-kernel> "N" <SMO-filterType>
<SMO-cost> ::=
<SMO-kernel> ::=
<SMO-filterType> ::=

<VotedPerceptron> ::= "VotedPerceptron"

<IBk> ::= "IBk"

<KStar> ::= "KStar"

<DecisionTable> ::= "DecisionTable"

<JRip> ::= "JRip"

<OneR> ::= "OneR"

<PART> ::= "PART"

<ZeroR> ::= "ZeroR"

<DecisionStump> ::= "DecisionStump"

<J48> ::= "J48" "A" <J48-useLaplace> "B" <J48-binarySplits> "J" <J48-useMDLcorrection>  "M" <J48-minNumObj>
          "O" <J48-collapseTree> "U" <J48-unpruned>
<J48-useLaplace> ::= "TRUE" | "FALSE"
<J48-binarySplits> ::= "TRUE" | "FALSE"
<J48-confidenceFactor> ::= "RANDOM_FLOAT [0.0, 1.0]"
<J48-useMDLcorrection> ::= "TRUE" | "FALSE"
<J48-minNumObj> ::= "RANDOM_INT [1, 64]"
<J48-collapseTree> ::= "TRUE" | "FALSE"
<J48-subtreeRaising> ::= "TRUE" | "FALSE"
<J48-unpruned> ::= "TRUE" | "FALSE" "C" <J48-confidenceFactor> "S" <J48-subtreeRaising>

<LMT> ::= "LMT" "A" <LMT-useAIC> "B" <LMT-convertNominal> "C" <LMT-fastRegression> "M" <LMT-minNumInstances>
          "P" <LMT-errorOnProbabilities> "R" <LMT-splitOnResiduals> "W" <LMT-weightTrimBeta>
<LMT-useAIC> ::= "TRUE" | "FALSE"
<LMT-convertNominal> ::= "TRUE" | "FALSE"
<LMT-fastRegression> ::= "TRUE" | "FALSE"
<LMT-minNumInstances> ::= "RANDOM_INT [1, 64]"
<LMT-errorOnProbabilities> ::= "TRUE" | "FALSE"
<LMT-splitOnResiduals> ::= "TRUE" | "FALSE"
<LMT-weightTrimBeta> ::= "0" | "RANDOM_FLOAT [0.0, 1.0]"

<RandomForest> ::= "RandomForest" "I" <RandomForest-numIterations> "K" <RandomForest-numFeatures>
                   "MD" <RandomForest-maxDepth>
<RandomForest-numIterations> ::= "RANDOM_INT [2, 256]"
<RandomForest-numFeatures> ::= "0" | "RANDOM_INT [1, 32]"
<RandomForest-maxDepth> ::= "0" | "RANDOM_INT [1, 20]"

<RandomTree> ::= "RandomTree" "K" <RandomTree-KValue> "M" <RandomTree-minNum> "N" <RandomTree-numFolds>
                 "U" <RandomTree-allowUnclassifiedInstances> "MD" <RandomTree-maxDepth>
<RandomTree-KValue> ::= "0" | "RANDOM_INT [2, 32]"
<RandomTree-minNum> ::= "RANDOM_INT [1, 64]"
<RandomTree-numFolds> ::= "0" | "RANDOM_INT [2, 5]"
<RandomTree-allowUnclassifiedInstances> ::= "TRUE" | "FALSE"
<RandomTree-maxDepth> ::= "0" | "RANDOM_INT [2, 20]"

<REPTree> ::= "REPTree" "L" <REPTree-maxDepth> "M" <REPTree-minNum> "P" <REPTree-noPruning>
              "V" <REPTree-minVarianceDrop>
<REPTree-maxDepth> ::= "-1" | "RANDOM_INT [2, 20]"
<REPTree-minNum> ::= "RANDOM_INT [1, 64]"
<REPTree-noPruning> ::= "TRUE" | "FALSE"
<REPTree-minVarianceDrop> ::= "RANDOM_FLOAT [1E-5, 1E-1]"

<Stacking> ::= "Stacking"

<Vote> ::= "Vote"
